---
Rakefile:
  requires:
    - 'puppet-strings/tasks'

spec/spec_helper.rb:
  mock_with: ':rspec'

spec/default_facts.yml:
  extra_facts:
    powershell_version: '5.1.14409.1012'

.gitlab-ci.yml:
  delete: true

appveyor.yml:
  unmanaged: true